"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
const NAV_GROUPS = [
 {label:"BUILD",items:[
  ["/dashboard","Dashboard","⌂"],["/dashboard/agents","Agents","◈"],["/dashboard/create","Create Agent","+"],["/dashboard/workflows","Workflows","↗"],["/dashboard/multi-agent","Multi-Agent","◇"],["/dashboard/tools","Tools","⚙"],["/dashboard/knowledge","Knowledge","▦"],["/dashboard/datasets","Datasets","▤"]]},
 {label:"QUALITY",items:[["/dashboard/runs","Runs","≡"],["/dashboard/evaluations","Evaluations","✓"],["/dashboard/observability","Observability","◉"]]},
 {label:"DEPLOY",items:[["/dashboard/deployments","Deployments","▲"],["/dashboard/api","API & SDK","⌘"],["/dashboard/api-keys","API Keys","#"],["/dashboard/webhooks","Webhooks","↪"]]},
 {label:"MANAGE",items:[["/dashboard/analytics","Analytics","◒"],["/dashboard/usage","Usage & Costs","$"],["/dashboard/security","Security","◆"],["/dashboard/audit-logs","Audit Logs","□"],["/dashboard/secrets","Secrets","*"],["/dashboard/integrations","Integrations","∞"]]},
 {label:"ECOSYSTEM",items:[["/dashboard/templates","Templates","▣"],["/dashboard/marketplace","Marketplace","◇"],["/dashboard/docs","Documentation","?"]]},
 {label:"WORKSPACE",items:[["/dashboard/team","Team","◎"],["/dashboard/billing","Billing","◫"],["/dashboard/notifications","Notifications","🔔"],["/dashboard/support","Support","✉"],["/dashboard/settings","Settings","⚙"]]},
] as const;
export function Sidebar({isAdmin,onNavigate}:{isAdmin:boolean;onNavigate?:()=>void}){const pathname=usePathname();return <aside className="w-64 shrink-0 border-r border-base-700 bg-base-900 lg:bg-base-900/80 min-h-screen p-4 flex flex-col overflow-y-auto h-full lg:sticky lg:top-0 lg:h-screen"><div className="px-2 py-2 mb-7 flex items-center justify-between"><Link href="/dashboard" className="font-display font-bold text-xl tracking-tight" onClick={onNavigate}>agent<span className="text-neon-cyan">mi</span></Link><span className="rounded-md border border-neon-cyan/20 bg-neon-cyan/5 px-2 py-1 text-[10px] font-mono text-neon-cyan">AI</span></div><nav className="flex-1 overflow-y-auto pr-1">{NAV_GROUPS.map(g=><div key={g.label} className="mb-5"><p className="px-3 mb-2 text-[10px] font-mono tracking-[0.18em] text-ink-600">{g.label}</p><div className="flex flex-col gap-1">{g.items.map(([href,label,icon])=>{const active=href==="/dashboard"?pathname===href:pathname===href||pathname.startsWith(`${href}/`);return <Link key={href} href={href} onClick={onNavigate} className={`group flex items-center gap-3 rounded-lg px-3 py-2 text-sm transition-colors ${active?"bg-neon-cyan/10 text-neon-cyan border border-neon-cyan/20":"text-ink-400 hover:text-ink-100 hover:bg-base-800 border border-transparent"}`}><span className="w-5 text-center text-xs" aria-hidden="true">{icon}</span><span>{label}</span></Link>})}</div></div>)}{isAdmin&&<Link href="/admin" onClick={onNavigate} className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-neon-violet border-t border-base-700 pt-4"><span className="h-2 w-2 rounded-full bg-neon-violet" aria-hidden="true"/>Admin Panel</Link>}</nav><div className="mt-4 rounded-xl border border-base-700 bg-base-800/60 p-3"><p className="text-xs font-medium">Agentmi Workspace</p><p className="text-[11px] text-ink-600 mt-1">Build · test · evaluate · deploy · observe.</p></div></aside>}
