"use client";
import {useMemo,useState} from "react";
import {useFormState,useFormStatus} from "react-dom";
import {saveWorkflowGraph,type SaveGraphState} from "@/lib/actions/workflow-graph";

export type Node={id:string;node_key:string;node_type:"start"|"agent"|"router"|"end";label:string;agent_id:string|null;position:{x:number;y:number}};
export type Edge={source_node_id:string;target_node_id:string;condition:Record<string,unknown>};
const initial:SaveGraphState={error:null};
function SaveButton(){const {pending}=useFormStatus();return <button className="btn-primary text-sm" disabled={pending}>{pending?"Saving…":"Save workflow"}</button>}
export function WorkflowBuilder({workflowId,agents,initialNodes,initialEdges}:{workflowId:string;agents:{id:string;name:string}[];initialNodes:Node[];initialEdges:Edge[]}){
 const [nodes,setNodes]=useState<Node[]>(initialNodes); const [edges,setEdges]=useState<Edge[]>(initialEdges); const [selected,setSelected]=useState<string|null>(null); const [state,action]=useFormState(saveWorkflowGraph,initial);
 const selectedNode=nodes.find(n=>n.id===selected);
 const graph=useMemo(()=>({workflowId,nodes,edges}),[workflowId,nodes,edges]);
 function add(type:Node["node_type"]){const id=crypto.randomUUID();const node={id,node_key:id,node_type:type,label:type==="agent"?"Agent step":type[0].toUpperCase()+type.slice(1),agent_id:type==="agent"?(agents[0]?.id??null):null,position:{x:80+nodes.length*30,y:80+nodes.length*20}};setNodes(v=>[...v,node]);if(nodes.length)setEdges(v=>[...v,{source_node_id:nodes[nodes.length-1].id,target_node_id:id,condition:{}}]);setSelected(id)}
 function update(p:Partial<Node>){if(!selected)return;setNodes(v=>v.map(n=>n.id===selected?{...n,...p}:n));}
 return <div className="space-y-4"><form action={action}><input type="hidden" name="graph" value={JSON.stringify(graph)}/><div className="flex items-center gap-2"><button type="button" onClick={()=>add("agent")} className="btn-secondary text-xs">+ Agent</button><button type="button" onClick={()=>add("router")} className="btn-secondary text-xs">+ Router</button><button type="button" onClick={()=>add("end")} className="btn-secondary text-xs">+ End</button><SaveButton/>{state.error&&<span className="text-neon-pink text-xs">{state.error}</span>}{state.ok&&<span className="text-neon-green text-xs">Saved</span>}</div></form>
 <div className="grid lg:grid-cols-[1fr_280px] gap-4"><div className="relative min-h-[560px] overflow-auto rounded-xl border border-base-700 bg-base-950 p-8"><svg className="absolute inset-0 w-full h-full pointer-events-none">{edges.map((e,i)=>{const a=nodes.find(n=>n.id===e.source_node_id),b=nodes.find(n=>n.id===e.target_node_id);if(!a||!b)return null;return <line key={i} x1={a.position.x+90} y1={a.position.y+40} x2={b.position.x+90} y2={b.position.y+40} stroke="currentColor" strokeWidth="2" className="text-neon-cyan/40"/>})}</svg>{nodes.map(n=><button type="button" key={n.id} onClick={()=>setSelected(n.id)} className={`absolute w-44 rounded-xl border p-3 text-left ${selected===n.id?"border-neon-cyan":"border-base-700"}`} style={{left:n.position.x,top:n.position.y}}><span className="text-[10px] uppercase text-ink-600">{n.node_type}</span><p className="font-bold text-sm">{n.label}</p>{n.agent_id&&<p className="text-xs text-ink-500">{agents.find(a=>a.id===n.agent_id)?.name??"Agent"}</p>}</button>)}</div><div className="neon-card p-4">{selectedNode?<><p className="font-bold mb-3">Node settings</p><label className="text-xs text-ink-500">Label</label><input value={selectedNode.label} onChange={e=>update({label:e.target.value})} className="w-full mt-1 mb-3 rounded-lg bg-base-900 border border-base-700 px-2 py-1.5 text-sm"/>{selectedNode.node_type==="agent"&&<><label className="text-xs text-ink-500">Agent</label><select value={selectedNode.agent_id??""} onChange={e=>update({agent_id:e.target.value||null})} className="w-full mt-1 rounded-lg bg-base-900 border border-base-700 px-2 py-1.5 text-sm">{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></>}</>:<p className="text-sm text-ink-500">Select a node to configure it.</p>}</div></div></div>
}
